config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :categories
  authenticated :user, ->(user){user.admin?} do
    get 'admin', to:"admin#index"
    get 'admin/show_article/:id',to: "admin#show_article" , as: "admin_article"
    get 'admin/comments'
    get 'admin/users'
    get 'admin/articles'
  end
  get 'search' , to: "search#index"
  # get 'users/profile'
  devise_for :users , controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id' , to: 'users#profile', as: "user"
  resources :after_signup

  resources :articles do
    resources :comments
  end
  get '/autocomplete', to: 'search#autocomplete'
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "home", to: "pages#home"
  # Defines the root path route ("/")
   root "pages#home"
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId

    validates :title, presence:true,length: {minimum:3, maximum:45}
    validates :body, presence:true , length: {minimum:1, maximu:300}
    belongs_to :user
    belongs_to :category
    has_rich_text :body
    has_many_attached :pictures
    has_many :comments , dependent: :destroy

    has_noticed_notifications model_name: "Notification"
    has_many :notifications, through: :user


    before_create :set_published_at
    after_create :publish_article
    friendly_id :title, use: %i[slugged history finders] # history to save old urls and redirect to the new url and finder here instead to change all article.friendly.find(params[:id]) and just become article.find(params[:id])

    def should_generate_new_friendly_id?
      title_changed? || slug.blank?
    end

    def views_by_day
      daily_events = Ahoy::Event.where("cast(properties ->> 'article_id' as bigint) = ?", id)
      daily_events.group_by_day(:time, range: 1.month.ago..Time.now).count
    end

    def self.total_views_by_day
      daily_events = Ahoy::Event.where(name: "Viewed article")
      daily_events.group_by_day(:time, range: 1.month.ago..Time.now).count
    end

    def publish_article
      PublishArticleJob.set(wait: (self.published_at - Time.now)).perform_later(self)
    end

    def publish!
      update(published: true)
    end

    def set_published_at
      self.published_at = Time.now if !self.published_at
    end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show update destroy]
  before_action :authenticate_user!
  # GET /articles or /articles.json
  def index
    @articles =
      Article.includes(%i[user rich_text_body]).paginate(
        page: params[:page],
        per_page: params[:per_page]
      )
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article.update(views: @article.views + 1)
    @comments =
      @article
        .comments
        .includes(%i[user rich_text_body])
        .order(created_at: :desc)
    ahoy.track "Viewed article", article_id: @article.id
    mark_notifications_as_read
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.includes([:rich_text_body]).find(params[:id])
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html do
          redirect_to article_url(@article),
                      notice: "Article was successfully created."
        end
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @article.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html do
          redirect_to article_url(@article),
                      notice: "Article was successfully updated."
        end
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @article.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html do
        redirect_to articles_url, notice: "Article was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.includes(%i[user rich_text_body]).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, :category_id, :published_at, pictures: [2])
  end

  def mark_notifications_as_read
    if current_user
      notifications_to_mark_as_read =
        @article.notifications_as_article.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div align="center" id="<%= dom_id article %>">

  <h2>
    <%= article.title %>
  </h2>
  <strong>Posted by: <span><%= (article.user.first_name).capitalize %></span> </strong>
  <h6> <%= pluralize(article.views,"view") %></h6>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.label :title, class: "input-group-text"%>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body, style: "display: block", class: "form-label" %>
    <%= form.rich_text_area :body, class: "form-control" %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :"post article at", class: "input-group-text" %>
    <%= form.datetime_field :published_at, class: "form-control" %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :category, class: "input-group-text" %>
    <%= form.select :category_id, options_for_select(Category.all.order(name: :desc).collect { |cat| [cat.name, cat.id] }), { prompt: "Select a category" }, class: "form-select" %>
  </div>

  <%= form.submit submit_text, class: "button mb-3" %>
<% end %>

app/views/articles/edit.html.erb
<div align="center" class="container">
<h1>Editing article</h1>

<%= render "form", article: @article, submit_text:"Update" %>

<br>

  <div align="center">
    <%= link_to "Show this article", @article,class:"btn btn-primary" %> |
    <%= link_to "Back to articles", articles_path,class:"btn btn-primary" %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container" , align="center">

<h1>Articles</h1>
</div>
<%= render 'categories/cat_form',articles: @articles.includes(:category) %>

app/views/articles/new.html.erb
<div align="center" class="container">

<h1>Create article</h1>
<%= render "form", article:@article, submit_text: "Post" %>
<p align="center"> <%= link_to "Back to articles", articles_path,class:"btn btn-primary" %> </p>

</div>

app/views/articles/show.html.erb
<div align="center" class=container>
  <%= area_chart @article.views_by_day, colors: ["#a00a"] %>

  <%= render @article %>

  <div align="center" class="btn-group">
      <%= link_to "Back to articles", articles_path, class:"btn btn-secondary border b-redius r-2" %>

   <% if current_user == @article.user || current_user.admin?%>

    <%= link_to "Edit this article", edit_article_path(@article), class:"btn btn-warning border b-redius r-2" %>
    <%= button_to "Destroy this article", @article, method: :delete,class:"btn btn-danger border b-redius r-2" %>

   <%end%>
  </div>
</div>
<br>


<div align="center" class=container>
  <%= render 'comments/form', article: @article,comment: @article.comments.build, submit_label:"Reply" %>

  <% @comments.each do |comment| %>
    <%= render 'comments/comment',article:@article , comment:comment %>
    <% end %>
</div>