config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :categories
  authenticated :user, ->(user){user.admin?} do
    get 'admin', to:"admin#index"
    get 'admin/show_article/:id',to: "admin#show_article" , as: "admin_article"
    get 'admin/comments'
    get 'admin/users'
    get 'admin/articles'
  end
  get 'search' , to: "search#index"
  # get 'users/profile'
  devise_for :users , controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id' , to: 'users#profile', as: "user"
  resources :after_signup

  resources :articles do
    resources :comments
  end
  get '/autocomplete', to: 'search#autocomplete'
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "home", to: "pages#home"
  # Defines the root path route ("/")
   root "pages#home"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, inverse_of: :address
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :country, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId

    validates :title, presence:true,length: {minimum:3, maximum:45}
    validates :body, presence:true , length: {minimum:1, maximu:300}
    belongs_to :user
    belongs_to :category
    has_rich_text :body
    has_many_attached :pictures
    has_many :comments , dependent: :destroy

    has_noticed_notifications model_name: "Notification"
    has_many :notifications, through: :user


    before_create :set_published_at
    after_create :publish_article
    friendly_id :title, use: %i[slugged history finders] # history to save old urls and redirect to the new url and finder here instead to change all article.friendly.find(params[:id]) and just become article.find(params[:id])

    def should_generate_new_friendly_id?
      title_changed? || slug.blank?
    end

    def views_by_day
      daily_events = Ahoy::Event.where("cast(properties ->> 'article_id' as bigint) = ?", id)
      daily_events.group_by_day(:time, range: 1.month.ago..Time.now).count
    end

    def self.total_views_by_day
      daily_events = Ahoy::Event.where(name: "Viewed article")
      daily_events.group_by_day(:time, range: 1.month.ago..Time.now).count
    end

    def publish_article
      PublishArticleJob.set(wait: (self.published_at - Time.now)).perform_later(self)
    end

    def publish!
      update(published: true)
    end

    def set_published_at
      self.published_at = Time.now if !self.published_at
    end


end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article , counter_cache: true
  belongs_to :user

  has_rich_text :body

after_create_commit :notify_recipient
before_destroy :cleanup_notifications
has_noticed_notifications model_name: 'Notification'

private

def notify_recipient
  return if article.user == user
  CommentNotification.with(Comment: self , article: article).deliver_later(article.user)
end

def cleanup_notifications
  notifications_as_comment.destroy_all
end

end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true

end

app/models/project.rb
class Project < ApplicationRecord
  has_rich_text :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles , dependent: :destroy
  has_many :comments , dependent: :destroy

  has_one_attached :avatar

  has_many :notifications, as: :recipient, dependent: :destroy

  has_one :address, dependent: :destroy, inverse_of: :user, autosave: true

  enum role: %i[user admin]
  after_initialize :set_default_role, if: :new_record?

  # Class level accessor http://apidock.com/rails/Class/cattr_accessor
  cattr_accessor :form_steps do
    %w[sign_up set_name set_address find_users]
  end

  # Instance level accessor http://apidock.com/ruby/Module/attr_accessor
  attr_accessor :form_step

  def form_step
    @form_step ||= 'sign_up'
  end

  with_options if: -> { required_for_step?('set_name') } do |step|
    step.validates :first_name, presence: true
    step.validates :last_name, presence: true
  end

  validates_associated :address, if: -> { required_for_step?('set_address') }

  def full_name
    "#{first_name.capitalize unless first_name.nil?} #{last_name.capitalize unless last_name.nil?}"
  end

  accepts_nested_attributes_for :address, allow_destroy: true

  def required_for_step?(step)
    # All fields are required if no form step is present
    form_step.nil?

    # All fields from previous steps are required if the
    # step parameter appears before or we are on the current step
    form_steps.index(step.to_s) <= form_steps.index(form_step.to_s)
  end

  private

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def show_article
    @post = Article.find(params[:id])
  end

  def comments
  end

  def users
    @users = User.all
  end

  def articles
    @articles =
      Article.includes(%i[user rich_text_body]).paginate(
        page: params[:page],
        per_page: params[:per_page]
      )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def profile
    @user.update!(views: @user.views + 1)
    @articles =
      @user.articles.includes(:rich_text_body).order(created_at: :desc)

    @total_views = 0
    @articles.each { |article| @total_views += article.views }
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_link.html.erb
<%= link_to resource.name,url_for([:admin,resource]),class:"btn btn-primary" %>

app/views/admin/_nav_links.html.erb
<div class="container text-center">
    <h1>Adminstrator</h1>

    <p >
        <%= link_to 'Admin', admin_path %> <%= " ->  #{params[:action].capitalize}" unless params[:action].eql?("index")%>
    </p>
    <div class="btn-group">
        <%= render 'admin/link',resource: Article %>
        <%= render 'admin/link',resource: User %>
    </div>
        <%= render 'total_views_by_day' %>

</div>

app/views/admin/_total_views_by_day.html.erb
<%= area_chart Article.total_views_by_day %>

app/views/admin/_user.html.erb
<div class="container card mt-3 mb-3">
  <h1><%= user.full_name %>'s Personal Home Page</h1>
  <p>You can read more about me, or checkout my blog.</p>
  <div class="card-actions mb-3">
    <%= link_to "Blog", user, class:"btn btn-primary" %>
  </div>

</div>

app/views/admin/articles.html.erb
    <%= render 'admin/nav_links' %>
    <%= render 'categories/cat_form',articles: @articles.includes(:user,:rich_text_body,:category) %>

app/views/admin/index.html.erb
<div class="container text-center">
    <%= render 'admin/nav_links' %>
</div>

app/views/admin/show_article.html.erb
<div class="container text-center">
    <%= render 'admin/nav_links' %>

    <div class="text-center mt-5">
        <div class="btn-group">
            <%= link_to "show", article_url(params[:id]), class:"btn btn-primary" %>
            <%= button_to 'Delete', article_url(params[:id]),method: :delete,class:"btn btn-danger" %>
        </div>

    </div>
</div>

app/views/admin/users.html.erb
<div class="container text-center">
    <%= render 'admin/nav_links' %>
</div>

<% @users.each do |user|%>
    <%= render 'user' , user:user%>
<%end%>

app/views/shared/_alerts.html.erb
<div class="container">
    <% if notice %>
    <p style="color green" class="notice"><%= notice %></p>
    <%end%>
    <% if alert %>
    <p style="color red" class="alert"><%= alert %></p>
    <%end%>
</div>

app/views/shared/_category.html.erb
<% if current_user && current_user.admin? %>

      <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'create',  new_category_path , class:"dropdown-item" %></li>
              <li><%= link_to 'Manage Categories', categories_path ,class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>

              <% categories.each do |cat| %>
                    <li><%= link_to cat.name,  cat , class:"dropdown-item" %></li>
              <% end %>
              <li><hr class="dropdown-divider"></li>
                <li><%= link_to "More",  categories_path , class:"dropdown-item" %></li>

            </ul>
      </li>
<% else %>
    <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                <% categories.each do |cat| %>
                    <li><%= link_to cat.name,  cat , class:"dropdown-item" %></li>
                <% end %>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "More",  categories_path , class:"dropdown-item" %></li>



            </ul>
      </li>

<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Hash Node', root_path, class:"navbar-brand", style:"font-family:sans-serif; font-weight: bold; font-style: italic;" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', home_path,class:"nav-link "  %>
        </li>

        <li class="nav-item">
            <%= link_to 'Blog', articles_path,class:"nav-link "  %>
        </li>

        <li class="nav-item">
            <%= link_to 'Portfolio', projects_path,class:"nav-link "  %>
        </li>

        <% if current_user %>
          <li class="nav-item">
            <%= link_to 'New article', new_article_path,class:"nav-link "  %>
          </li>
        <% end %>

        <%= render 'shared/category', categories: @categories %>

        <li class="nav-item">
            <%= render 'shared/notifications' %>
        </li>


      </ul>
      <ul class="navbar-nav me-0">
      <%= render 'shared/session' %>
      <%= render 'search/form' %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notification.html.erb
<li class="dropdown-item" >

  <%= link_to notification.to_notification.message, notification.to_notification.url,style:"text-decoration: none;"  %>
</li>

app/views/shared/_notifications.html.erb
<% if current_user %>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <span class="badge rounded-pill bg-danger">
        <%= @unread.count >= 9 ? "9+" : @unread.count %> <i class="bi bi-suit-heart-fill"></i>
      </span>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown" style="text decoration:non;">
      <% @unread.each do |notification| %>
        <%= render 'shared/notification', notification: notification %>
      <% end %>
      <% if @read.count > 0 && @unread.count > 0 %>
        <li>
          <hr class="dropdown-divider">
        </li>
      <% elsif @read.count + @unread.count == 0 %>
        <li class="dropdown-item">
          No notifications yet.
        </li>
      <% end %>
      <% @read.each do |notification| %>
        <%= render 'shared/notification', notification: notification %>
      <% end %>
    </ul>
  </li>

<% end %>

app/views/shared/_session.html.erb
<% if current_user %>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.first_name %>
        </a>
        <ul class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
            <li><%= link_to "Admin", admin_path, class:"dropdown-item" if current_user.admin? %></li>
            <li><%= link_to "New project", new_project_path,class:"dropdown-item" if current_user.admin? %></li>
            <li><%= link_to 'Profile', user_path(current_user),method: :delete ,class:"dropdown-item" %></li>
            <li><%= link_to 'Settings', edit_user_registration_path(current_user), class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to 'Sign out', destroy_user_session_path,method: :delete ,class:"dropdown-item" %></li>
        </ul>
    </li>


<% else %>
    <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Sign in
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><%= link_to 'Sign in',  new_user_session_path , class:"dropdown-item" %></li>
        <li><hr class="dropdown-divider"></li>
        <li><%= link_to 'Sign up', new_user_registration_path ,class:"dropdown-item" %></li>
    </ul>
    </li>
<% end %>