config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :categories
  authenticated :user, ->(user){user.admin?} do
    get 'admin', to:"admin#index"
    get 'admin/show_article/:id',to: "admin#show_article" , as: "admin_article"
    get 'admin/comments'
    get 'admin/users'
    get 'admin/articles'
  end
  get 'search' , to: "search#index"
  # get 'users/profile'
  devise_for :users , controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id' , to: 'users#profile', as: "user"
  resources :after_signup

  resources :articles do
    resources :comments
  end
  get '/autocomplete', to: 'search#autocomplete'
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "home", to: "pages#home"
  # Defines the root path route ("/")
   root "pages#home"
end

app/models/project.rb
class Project < ApplicationRecord
  has_rich_text :body
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :is_admin? , except: %i[index , show]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :link, :body)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
<div class="row">
  <div class="col-8">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="col-4">
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>
</div>
  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <div class="container">
    <div class="row">
        <h2 class="col-md-8"><%= project.title.titleize %></h2>


        <div class="col-md-4">
          <a href="<%= project.link %>" target="_blank"><%= project.title %></a>
        </div>
    </div>
    <div>
      <%= project.rich_text_body %>
    </div>

  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @project %>
<div align="center">
  <div class="btn-group col">
    <%= link_to "Edit this project", edit_project_path(@project), class:"btn btn-warning" if current_user&.admin? %> |
    <%= link_to "Back to projects", projects_path,class:"btn btn-primary" %>

    <%= button_to "Destroy this project", @project,class:"btn btn-danger", method: :delete if current_user&.admin? %>
  </div>
  </div>

  </div>